export enum GENERAL_SETTING_KEY {
    is_address_auto_typed = 'is_address_auto_typed',
    default_activity_time_interval = 'default_activity_time_interval',
    is_memo_allowed_in_deal_lost = 'is_memo_allowed_in_deal_lost',
    is_memo_allowed_in_activity_result = 'is_memo_allowed_in_activity_result',
    lead_name_settings = 'lead_name_settings',
    deal_closing_date_color_settings_time_frame = 'deal_closing_date_color_settings_time_frame',
    deal_closing_date_color_settings_neutral_color = 'deal_closing_date_color_settings_neutral_color',
    deal_closing_date_color_settings_warning_color = 'deal_closing_date_color_settings_warning_color',
    deal_closing_date_color_settings_passed_due_color = 'deal_closing_date_color_settings_passed_due_color',
    is_sub_account_enable = 'is_sub_account_enable',
    deal_name_settings = 'deal_name_settings',
    default_activity_availability = 'default_activity_availability',
    mail_undo_send = 'mail_undo_send',
}